<div class="sub_content">
<div>Your Accounts</div>
<div>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <th class="left">Account Type</th>
    <th class="left">Account Name</th>
    <th class="left">Account Number</th>
    <th>Account Balance</th>
    <th>Currency</th>
    <th>Cr/Dr</th>
  </tr>
  <tr>
    <td>Saving Account</td>
    <td>W.S.D Test Account</td>
    <td>77288299911</td>
    <td class="center">2,900,99</td>
    <td class="center">LKR</td>
    <td class="center">Cr</td>
  </tr>
</table>
</div>
</div>