<div class="sub_content">
<div>Dialog Bill Payment</div>
<div class="form_content">
<form id="frmDialog">
<div>
	<div>Pay To:</div>
    <div>Dialog</div>
</div>
<div>
	<div>Address</div>
    <div>No 10, Galle R0ad</div>
</div>
 <div>
 	<div>Phone Number</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Account Number</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Re-Type Account Number</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Amount</div>
    <input type="text" maxlength="4" />
 </div>
 <div>
     <input type="submit" value="Pay" style="margin-left:340px;"/>
 </div>
 </form>
</div>
</div>