<div class="sub_content">
<div>Money Transfer</div>
<div class="form_content">
<form>
 <div>
 	<div>From Account</div>
    <select>
    	<option value="22333333">W.C.S Test Account [9990000288982]</option>
    </select>
 </div>
 <div>
 	<div>To Account</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Transfer Amount</div>
    <input type="text" maxlength="5" />
 </div>
 <div>
 	<div>Transfer Note</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
     <input type="submit" value="Transfer" style="margin-left:340px;"/>
 </div>
 </form>
</div>
</div>