package org.team5.portal.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.sribank.org.portal.BankPortalService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-01-18T01:40:15.813+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "BankPortalServiceImplService", 
                  wsdlLocation = "http://ec2-67-202-56-114.compute-1.amazonaws.com:20081/portal-core/PortalService?wsdl",
                  targetNamespace = "http://impl.service.portal.team5.org/") 
public class BankPortalServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.portal.team5.org/", "BankPortalServiceImplService");
    public final static QName BankPortalServiceImplPort = new QName("http://impl.service.portal.team5.org/", "BankPortalServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-67-202-56-114.compute-1.amazonaws.com:20081/portal-core/PortalService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankPortalServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-67-202-56-114.compute-1.amazonaws.com:20081/portal-core/PortalService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankPortalServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankPortalServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankPortalServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BankPortalService
     */
    @WebEndpoint(name = "BankPortalServiceImplPort")
    public BankPortalService getBankPortalServiceImplPort() {
        return super.getPort(BankPortalServiceImplPort, BankPortalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankPortalService
     */
    @WebEndpoint(name = "BankPortalServiceImplPort")
    public BankPortalService getBankPortalServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BankPortalServiceImplPort, BankPortalService.class, features);
    }

}
