package com.dialog.org.billing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-01-18T01:48:30.913+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://org.dialog.com/billing", name = "BillPaymentListenerService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillPaymentListenerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "billPaid", targetNamespace = "http://org.dialog.com/billing", className = "com.dialog.org.billing.BillPaid")
    @WebMethod
    @ResponseWrapper(localName = "billPaidResponse", targetNamespace = "http://org.dialog.com/billing", className = "com.dialog.org.billing.BillPaidResponse")
    public boolean billPaid(
        @WebParam(name = "arg0", targetNamespace = "")
        com.dialog.org.billing.BillReceipt arg0
    );
}
