<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SriBank - Online Banking Portal</title>
<link href="<?php echo $this->baseUrl('/css/personal.css'); ?>" rel="stylesheet" type="text/css" />
<?php echo $this->headScript(); ?>
</head>

<body>

<div class="layout_wrapper">
  <div class="layout_header"> Welcome to SriBank Online Banking </div>
  <div class="content_wrapper"> 
  	<div class="left_panel">
    	<div><a href="<?php echo $this->baseUrl(HOST_PATH_DEFAULT.'/index/accounts'); ?>" >Accounts</a></div>
        <div><a href="<?php echo $this->baseUrl(HOST_PATH_DEFAULT.'/transfer'); ?>" >Money Tarnsfer</a></div>
        <div><a href="<?php echo $this->baseUrl(HOST_PATH_DEFAULT.'/billing'); ?>" >Bill Payment</a></div>
        <div><a href="<?php echo $this->baseUrl(HOST_PATH_DEFAULT.'/credit'); ?>" >Credit Card Transactions</a></div>
    </div>
    
    <div class="data_wrapper">
    <?php echo $this->layout()->content ?>
    </div>
  </div>
</div>
<div class="layout_footer"> Powered by SriBank 2012 </div>
</body>
</html>


</body>

</html>

