package dialog.gsm.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.dialog.org.billing.BillPaymentListenerService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-01-18T00:30:00.195+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "BillPaymentListenerServiceImplService", 
                  wsdlLocation = "http://ec2-67-202-56-114.compute-1.amazonaws.com:20090/dialog-gsm-bill-service/PayBill?wsdl",
                  targetNamespace = "http://impl.gsm.dialog/") 
public class BillPaymentListenerServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.gsm.dialog/", "BillPaymentListenerServiceImplService");
    public final static QName BillPaymentListenerServiceImplPort = new QName("http://impl.gsm.dialog/", "BillPaymentListenerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-67-202-56-114.compute-1.amazonaws.com:20090/dialog-gsm-bill-service/PayBill?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillPaymentListenerServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-67-202-56-114.compute-1.amazonaws.com:20090/dialog-gsm-bill-service/PayBill?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillPaymentListenerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillPaymentListenerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillPaymentListenerServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BillPaymentListenerService
     */
    @WebEndpoint(name = "BillPaymentListenerServiceImplPort")
    public BillPaymentListenerService getBillPaymentListenerServiceImplPort() {
        return super.getPort(BillPaymentListenerServiceImplPort, BillPaymentListenerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillPaymentListenerService
     */
    @WebEndpoint(name = "BillPaymentListenerServiceImplPort")
    public BillPaymentListenerService getBillPaymentListenerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BillPaymentListenerServiceImplPort, BillPaymentListenerService.class, features);
    }

}
