package com.sribank.org.portal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-01-18T01:40:15.803+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://org.sribank.com/portal", name = "BankPortalService")
@XmlSeeAlso({ObjectFactory.class})
public interface BankPortalService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccountList", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetAccountList")
    @WebMethod
    @ResponseWrapper(localName = "getAccountListResponse", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetAccountListResponse")
    public java.util.List<com.sribank.org.portal.Account> getAccountList(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "loginToken", targetNamespace = "")
        java.lang.String loginToken
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccountHistory", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetAccountHistory")
    @WebMethod
    @ResponseWrapper(localName = "getAccountHistoryResponse", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetAccountHistoryResponse")
    public java.util.List<com.sribank.org.portal.Transaction> getAccountHistory(
        @WebParam(name = "accountNumber", targetNamespace = "")
        java.lang.String accountNumber,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "loginToken", targetNamespace = "")
        java.lang.String loginToken
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCreditCardList", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetCreditCardList")
    @WebMethod
    @ResponseWrapper(localName = "getCreditCardListResponse", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetCreditCardListResponse")
    public java.util.List<com.sribank.org.portal.CreditCardAccount> getCreditCardList(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "loginToken", targetNamespace = "")
        java.lang.String loginToken
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCreditCardTransactionByCardId", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetCreditCardTransactionByCardId")
    @WebMethod
    @ResponseWrapper(localName = "getCreditCardTransactionByCardIdResponse", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.GetCreditCardTransactionByCardIdResponse")
    public java.util.List<com.sribank.org.portal.Transaction> getCreditCardTransactionByCardId(
        @WebParam(name = "cardId", targetNamespace = "")
        java.lang.String cardId,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "loginToken", targetNamespace = "")
        java.lang.String loginToken
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.Transfer")
    @WebMethod
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://org.sribank.com/portal", className = "com.sribank.org.portal.TransferResponse")
    public com.sribank.org.portal.FundTransferResponse transfer(
        @WebParam(name = "request", targetNamespace = "")
        com.sribank.org.portal.FundTransferRequest request
    );
}
