<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome to SriBank</title>
<link href="<?php echo $this->baseUrl(); ?>/css/login.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="login_wrapper">
  <div class="login_header"> Welcome to SriBank Online Banking </div>
  <div class="personal_login"> 
	<div class="hdr">Login - Personal Banking</div>
    <form id="frmLogin" method="post">
    <div class="frm-row">
      <div class="form_label">User Name</div>
      <div class="txt-box-field"><input type="text" class="txtBox" /></div>
    </div>
     <div class="frm-row">
      <div class="form_label">Password</div>
      <div class="txt-box-field"><input type="password" class="txtBox" /></div>
    </div>
    <div class="frm-row">
      <div class="form_label"></div>
      <div class="txt-box-field" style="text-align:right;margin:10px;"><input type="submit" value="Login" class="btnCommand" /></div>
    </div>
    </form>
  </div>
</div>
<div class="login_footer"> Powered by SriBank 2012 </div>
</body>
</html>
