<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
</head>

<body>
  Hello,</p>
                          <p>We are pleased to inform you that your UberDash user account has been created.</p>
<p>Please find your account details bellow.</p>
<p><strong>Email :</strong> <?php echo $this->Email; ?></p>
                          <p><strong>PIN:</strong> <?php echo $this->Pin; ?></p>
                          <p>Thank you,</p>
                          <p>UberDash Team<br />
                            <br />
                          </p>
</body>
</html>