<div class="sub_content">
<div> Bill Payment</div>
<div class="form_content">
<form id="frmPay">
 <div>
 	<div>Pay to</div>
    <select name="cboPayTo">
    	<option value="1">Dialog</option>
        <option value="2">Electricity Board</option>
        <option value="3">Water Board</option>
    </select>
 </div>
 <div>
 	<div>Account Number</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Re-Type Account Number</div>
    <input type="text" maxlength="10" />
 </div>
 <div>
 	<div>Amount</div>
    <input type="text" maxlength="4" />
 </div>
 <div>
     <input type="submit" value="Pay" style="margin-left:340px;"/>
 </div>
 </form>
</div>
</div>